[context.production]
  environment = { STRIPE="pk_test_51JMUBKHsfCEsT9ywSOD8mQVzGT5eOpTybYhmHk0mksyyhameQKGkG1AmcMzRrO6Qv2rHZPXK7JYWpe3BwnhJKnmT00pjkhy6aU" }

# The following redirect is intended for use with most SPAs that handle
# routing internally.

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Credentials = "true"